-- PMO CTSB: apply current client / project schema (idempotent — safe to run more than once)
-- Run in Supabase SQL Editor, or: npm run db:migrate (requires SUPABASE_DB_URL in .env)

-- 1) Companies (clients) + PICs (client_contacts)
create table if not exists public.client_contacts (
  id bigint primary key generated by default as identity,
  client_id bigint not null references public.clients(id) on delete cascade,
  contact_name text,
  email text,
  phone text,
  created_at timestamptz not null default now()
);

create index if not exists idx_client_contacts_client_id on public.client_contacts(client_id);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'clients' and column_name = 'contact_name'
  ) then
    insert into public.client_contacts (client_id, contact_name, email, phone, created_at)
    select
      c.id,
      c.contact_name,
      c.email,
      c.phone,
      coalesce(c.created_at, now())
    from public.clients c
    where (
        coalesce(c.contact_name, '') <> ''
        or coalesce(c.email, '') <> ''
        or coalesce(c.phone, '') <> ''
      )
      and not exists (
        select 1 from public.client_contacts cc where cc.client_id = c.id
      );

    alter table public.clients drop column contact_name;
    alter table public.clients drop column email;
    alter table public.clients drop column phone;
  end if;
end $$;

-- 2) Many clients per project (project_clients)
create table if not exists public.project_clients (
  id bigint primary key generated by default as identity,
  project_id bigint not null references public.projects(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (project_id, client_id)
);

create index if not exists idx_project_clients_project_id on public.project_clients(project_id);
create index if not exists idx_project_clients_client_id on public.project_clients(client_id);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'projects' and column_name = 'client_id'
  ) then
    insert into public.project_clients (project_id, client_id, created_at)
    select
      p.id,
      p.client_id,
      coalesce(p.created_at, now())
    from public.projects p
    where p.client_id is not null
      and not exists (
        select 1 from public.project_clients pc
        where pc.project_id = p.id and pc.client_id = p.client_id
      );

    alter table public.projects drop column client_id;
  end if;
end $$;
