-- PMO CTSB Supabase schema
-- Run in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists clients (
  id bigint primary key generated by default as identity,
  name text not null,
  contact_name text,
  email text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists people (
  id bigint primary key generated by default as identity,
  name text not null,
  email text,
  role text,
  created_at timestamptz not null default now()
);

create table if not exists projects (
  id bigint primary key generated by default as identity,
  name text not null,
  description text,
  status text not null default 'active',
  start_date date,
  end_date date,
  client_id bigint references clients(id) on delete set null,
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists project_assignments (
  id bigint primary key generated by default as identity,
  project_id bigint not null references projects(id) on delete cascade,
  person_id bigint not null references people(id) on delete cascade,
  role_in_project text,
  allocation_percent int not null default 100,
  created_at timestamptz not null default now(),
  unique(project_id, person_id)
);

create table if not exists activities (
  id bigint primary key generated by default as identity,
  person_id bigint not null,
  project_id bigint references projects(id) on delete set null,
  type text not null,
  title text not null,
  description text,
  location text not null default '—',
  start_at timestamptz not null,
  end_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists project_tasks (
  id bigint primary key generated by default as identity,
  project_id bigint not null references projects(id) on delete cascade,
  name text not null,
  planned_start_date date,
  planned_end_date date,
  actual_start_date date,
  actual_end_date date,
  progress_percent int not null default 0,
  sort_order int not null default 0,
  status text not null default 'new',
  assignee_id bigint,
  parent_id bigint references project_tasks(id) on delete set null,
  task_kind text not null default 'task',
  created_at timestamptz not null default now()
);

create table if not exists users_app (
  id bigint primary key generated by default as identity,
  name text not null,
  email text not null unique,
  role text not null default 'user',
  active boolean not null default true,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists sessions_app (
  id bigint primary key generated by default as identity,
  user_id bigint not null references users_app(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists settings_app (
  id int primary key default 1,
  activity_locations jsonb not null default '[]'::jsonb,
  reference_office_name text not null default 'Main Office',
  mileage_from_office_km jsonb not null default '{}'::jsonb,
  general_notes text not null default '',
  currency_code text not null default 'MYR',
  updated_at timestamptz not null default now(),
  constraint one_row check (id = 1)
);

create table if not exists audit_log (
  id bigint primary key generated by default as identity,
  at timestamptz not null default now(),
  user_id bigint,
  user_email text,
  user_name text,
  action text not null,
  target_type text not null,
  target_id bigint,
  summary text not null,
  detail jsonb
);

insert into settings_app (id) values (1)
on conflict (id) do nothing;
