/**
 * Ensure clients short_code/logo_url + client_contacts (+ project_clients) exist.
 * Usage: node scripts/ensureClientsColumns.mjs
 */
import 'dotenv/config';
import pg from 'pg';

const url = process.env.SUPABASE_DB_URL || process.env.DATABASE_URL;
if (!url) {
  console.error('Missing SUPABASE_DB_URL / DATABASE_URL');
  process.exit(1);
}

const pool = new pg.Pool({ connectionString: url, ssl: { rejectUnauthorized: false } });

try {
  await pool.query(`
    alter table public.clients add column if not exists short_code text;
    alter table public.clients add column if not exists logo_url text;
    create index if not exists clients_short_code_idx on public.clients (short_code);

    create table if not exists public.client_contacts (
      id bigint primary key generated by default as identity,
      client_id bigint not null references public.clients(id) on delete cascade,
      contact_name text,
      email text,
      phone text,
      created_at timestamptz not null default now()
    );
    create index if not exists idx_client_contacts_client_id on public.client_contacts(client_id);

    create table if not exists public.project_clients (
      id bigint primary key generated by default as identity,
      project_id bigint not null references public.projects(id) on delete cascade,
      client_id bigint not null references public.clients(id) on delete cascade,
      created_at timestamptz not null default now(),
      unique (project_id, client_id)
    );
    create index if not exists idx_project_clients_project_id on public.project_clients(project_id);
    create index if not exists idx_project_clients_client_id on public.project_clients(client_id);
  `);
  try {
    await pool.query("NOTIFY pgrst, 'reload schema'");
  } catch (e) {
    console.warn('schema reload notify skipped:', e.message);
  }

  const tables = await pool.query(`
    select table_name
    from information_schema.tables
    where table_schema = 'public'
      and table_name in ('client_contacts', 'project_clients')
    order by table_name
  `);
  const cols = await pool.query(`
    select column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'clients'
      and column_name in ('short_code', 'logo_url')
    order by column_name
  `);
  console.log('tables present:', tables.rows.map((r) => r.table_name).join(', ') || '(none)');
  console.log('clients columns present:', cols.rows.map((r) => r.column_name).join(', ') || '(none)');
} finally {
  await pool.end();
}
