/**
 * Create attachments_app if missing, then verify insert.
 * Usage: node scripts/ensureAttachmentsApp.mjs
 */
import 'dotenv/config';
import pg from 'pg';
import { getSupabaseDbUrl } from '../lib/dbConnection.js';

const url = getSupabaseDbUrl();
if (!url) {
  console.error('Missing SUPABASE_DB_URL / DATABASE_URL / SUPABASE_DB_PASSWORD');
  process.exit(1);
}

const pool = new pg.Pool({ connectionString: url, ssl: { rejectUnauthorized: false } });

const ddl = `
create table if not exists public.attachments_app (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  kind text not null default 'file',
  file_name text not null,
  mime_type text,
  file_size bigint,
  storage_path text,
  external_url text,
  label text,
  uploaded_by_user_id bigint,
  created_at timestamptz not null default now()
);
create index if not exists idx_attachments_app_entity
  on public.attachments_app (entity_type, entity_id);
alter table public.attachments_app enable row level security;
`;

try {
  await pool.query(ddl);
  try {
    await pool.query("NOTIFY pgrst, 'reload schema'");
  } catch (e) {
    console.warn('schema reload notify skipped:', e.message);
  }

  const t = await pool.query(`select to_regclass('public.attachments_app') as rel`);
  console.log('table:', t.rows[0]?.rel);

  const ins = await pool.query(`
    insert into public.attachments_app (entity_type, entity_id, kind, file_name, mime_type)
    values ('backlog', 1, 'file', 'schema-check.txt', 'text/plain')
    returning id
  `);
  console.log('insert ok:', ins.rows[0]);
  await pool.query(`delete from public.attachments_app where id = $1`, [ins.rows[0].id]);
  console.log('cleaned');
} catch (e) {
  console.error('FAILED:', e.message || e);
  process.exitCode = 1;
} finally {
  await pool.end();
}
