/**
 * Create notifications_app if missing, then verify insert.
 * Usage: node scripts/ensureNotificationsApp.mjs
 */
import 'dotenv/config';
import pg from 'pg';

const url = process.env.SUPABASE_DB_URL || process.env.DATABASE_URL;
if (!url) {
  console.error('Missing SUPABASE_DB_URL / DATABASE_URL');
  process.exit(1);
}

const pool = new pg.Pool({ connectionString: url, ssl: { rejectUnauthorized: false } });

const ddl = `
create table if not exists public.notifications_app (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  type text not null default 'info',
  title text not null,
  body text,
  link text,
  entity_type text,
  entity_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_app_user_idx
  on public.notifications_app (user_id, read_at);
create index if not exists idx_notifications_app_user_created
  on public.notifications_app (user_id, created_at desc);
alter table public.notifications_app enable row level security;
`;

try {
  await pool.query(ddl);
  try {
    await pool.query("NOTIFY pgrst, 'reload schema'");
  } catch (e) {
    console.warn('schema reload notify skipped:', e.message);
  }

  const t = await pool.query(`select to_regclass('public.notifications_app') as rel`);
  console.log('table:', t.rows[0]?.rel);

  const ins = await pool.query(`
    insert into public.notifications_app (user_id, type, title, body, link)
    values (56, 'info', 'Schema check', 'notifications_app ready', '/calendar')
    returning id
  `);
  console.log('insert ok:', ins.rows[0]);
  await pool.query(`delete from public.notifications_app where id = $1`, [ins.rows[0].id]);
  console.log('cleaned');
} catch (e) {
  console.error('FAILED:', e.message || e);
  process.exitCode = 1;
} finally {
  await pool.end();
}
