/**
 * Stateless clients repository — Supabase when configured, in-memory when ALLOW_LOCAL_STORE only.
 */
import { formatClientNames, normalizeProjectClientIds } from '../../lib/projectClients.js';
import { nextId } from '../runtime/helpers.js';
import { isDbMode, dbSelect, dbInsert, dbUpdate, dbDelete, dbDeleteWhere } from '../runtime/query.js';

function isMissingColumnError(err) {
  const msg = String(err?.message || err || '');
  return /schema cache|PGRST204|does not exist|column .* does not exist/i.test(msg);
}

/** Best-effort DDL so clients columns + PIC/link tables exist on older production DBs. */
async function ensureClientsSchema() {
  try {
    const { getPgPool } = await import('../runtime/pgPool.js');
    const pool = getPgPool();
    if (!pool) return false;
    await pool.query(`
      alter table public.clients add column if not exists short_code text;
      alter table public.clients add column if not exists logo_url text;
      create index if not exists clients_short_code_idx on public.clients (short_code);

      create table if not exists public.client_contacts (
        id bigint primary key generated by default as identity,
        client_id bigint not null references public.clients(id) on delete cascade,
        contact_name text,
        email text,
        phone text,
        created_at timestamptz not null default now()
      );
      create index if not exists idx_client_contacts_client_id on public.client_contacts(client_id);

      create table if not exists public.project_clients (
        id bigint primary key generated by default as identity,
        project_id bigint not null references public.projects(id) on delete cascade,
        client_id bigint not null references public.clients(id) on delete cascade,
        created_at timestamptz not null default now(),
        unique (project_id, client_id)
      );
      create index if not exists idx_project_clients_project_id on public.project_clients(project_id);
      create index if not exists idx_project_clients_client_id on public.project_clients(client_id);
    `);
    try {
      await pool.query("NOTIFY pgrst, 'reload schema'");
    } catch {
      /* best-effort PostgREST cache reload */
    }
    await new Promise((r) => setTimeout(r, 500));
    return true;
  } catch (e) {
    console.warn('ensureClientsSchema failed:', e?.message || e);
    return false;
  }
}

function missingClientsSchemaMessage(err) {
  const msg = String(err?.message || err || '');
  if (/client_contacts/i.test(msg)) {
    return (
      'Cannot save PIC: the client_contacts table is missing. '
      + 'Run migration `20260910150000_ensure_client_contacts_project_clients.sql` '
      + '(or set SUPABASE_DB_URL so the API can create it).'
    );
  }
  if (/project_clients/i.test(msg)) {
    return (
      'Cannot link project clients: the project_clients table is missing. '
      + 'Run migration `20260910150000_ensure_client_contacts_project_clients.sql` '
      + '(or set SUPABASE_DB_URL so the API can create it).'
    );
  }
  if (/short_code/i.test(msg)) {
    return (
      'Cannot save short code: the clients.short_code column is missing. '
      + 'Run migration `20260910150000_ensure_client_contacts_project_clients.sql` '
      + '(or set SUPABASE_DB_URL so the API can add it).'
    );
  }
  if (/logo_url/i.test(msg)) {
    return (
      'Cannot save logo: the clients.logo_url column is missing. '
      + 'Run migration `20260910150000_ensure_client_contacts_project_clients.sql` '
      + '(or set SUPABASE_DB_URL so the API can add it).'
    );
  }
  return msg || 'Client operation failed because required schema is missing';
}

export function createClientsRepository(ctx, getStore) {
  const { getData, save } = ctx;

  async function listClients() {
    if (!isDbMode()) return [...getData().clients];
    return dbSelect('clients', { order: 'id' });
  }

  async function listClientsByIds(ids = []) {
    const want = [...new Set((ids || []).map(Number).filter((id) => Number.isFinite(id) && id > 0))];
    if (!want.length) return [];
    if (!isDbMode()) {
      return (getData().clients || []).filter((c) => want.includes(Number(c.id)));
    }
    return dbSelect('clients', {
      columns: 'id,name',
      inFilters: { id: want },
      order: 'id',
    });
  }

  async function listClientContacts() {
    if (!isDbMode()) return [...(getData().client_contacts || [])];
    try {
      return await dbSelect('client_contacts', { order: 'id' });
    } catch (e) {
      if (!isMissingColumnError(e) || !/client_contacts/i.test(String(e?.message || e || ''))) throw e;
      const ensured = await ensureClientsSchema();
      if (!ensured) return [];
      try {
        return await dbSelect('client_contacts', { order: 'id' });
      } catch (retryErr) {
        if (isMissingColumnError(retryErr)) return [];
        throw retryErr;
      }
    }
  }

  async function listProjectClients() {
    if (!isDbMode()) return [...(getData().project_clients || [])];
    return dbSelect('project_clients', { order: 'id' });
  }

  async function getClientById(id) {
    if (!isDbMode()) return getData().clients.find((c) => Number(c.id) === Number(id)) || null;
    return dbSelect('clients', { filters: { id: Number(id) }, maybeSingle: true });
  }

  return {
    /** @deprecated Prefer listClients() — sync getter is local-only. */
    get clients() {
      return [...getData().clients];
    },
    get client_contacts() {
      return [...(getData().client_contacts || [])];
    },
    get project_clients() {
      return [...(getData().project_clients || [])];
    },

    listClients,
    listClientsByIds,
    listClientContacts,
    listProjectClients,
    getClientById,

    async getClientsForProject(projectId) {
      const pid = Number(projectId);
      if (!isDbMode()) {
        const data = getData();
        const links = (data.project_clients || []).filter((pc) => Number(pc.project_id) === pid);
        return links
          .map((pc) => data.clients.find((c) => Number(c.id) === Number(pc.client_id)))
          .filter(Boolean)
          .sort((a, b) => (a.name || '').localeCompare(b.name || ''));
      }
      try {
        const links = await dbSelect('project_clients', { filters: { project_id: pid } });
        if (!links.length) return [];
        const ids = links.map((l) => l.client_id);
        const clients = await dbSelect('clients', { inFilters: { id: ids } });
        return clients.sort((a, b) => (a.name || '').localeCompare(b.name || ''));
      } catch (e) {
        console.warn('getClientsForProject failed:', e?.message || e);
        return [];
      }
    },

    async getClientIdsForProject(projectId) {
      const clients = await getStore().getClientsForProject(projectId);
      return clients.map((c) => c.id);
    },

    async linkProjectClient(projectId, clientId) {
      const cid = +clientId;
      if (!Number.isFinite(cid) || cid <= 0) return false;
      await getStore().setProjectClients(projectId, [cid]);
      return true;
    },

    async setProjectClients(projectId, clientIds) {
      const pid = +projectId;
      const ids = normalizeProjectClientIds(clientIds);
      if (!isDbMode()) {
        const data = getData();
        if (!data.project_clients) data.project_clients = [];
        const prev = (data.project_clients || [])
          .filter((pc) => Number(pc.project_id) === pid)
          .map((pc) => Number(pc.client_id))
          .sort((a, b) => a - b);
        const next = [...ids].sort((a, b) => a - b);
        if (prev.length === next.length && prev.every((v, i) => v === next[i])) return;
        data.project_clients = data.project_clients.filter((pc) => Number(pc.project_id) !== pid);
        ids.forEach((cid) => {
          if (data.clients.some((c) => Number(c.id) === cid)) {
            data.project_clients.push({
              id: nextId(data.project_clients),
              project_id: pid,
              client_id: cid,
              created_at: new Date().toISOString(),
            });
          }
        });
        save();
        return;
      }
      const existingLinks = await dbSelect('project_clients', { filters: { project_id: pid } });
      const prev = (existingLinks || []).map((pc) => Number(pc.client_id)).sort((a, b) => a - b);
      const next = [...ids].sort((a, b) => a - b);
      if (prev.length === next.length && prev.every((v, i) => v === next[i])) return;

      await dbDeleteWhere('project_clients', { project_id: pid });
      if (!ids.length) return;
      const rows = ids.map((cid) => ({
        project_id: pid,
        client_id: cid,
        created_at: new Date().toISOString(),
      }));
      const { dbInsertMany } = await import('../runtime/query.js');
      await dbInsertMany('project_clients', rows, { returning: false });
    },

    async projectWithClients(project) {
      if (!project) return project;
      let clients = [];
      try {
        clients = await getStore().getClientsForProject(project.id);
      } catch (e) {
        console.warn('projectWithClients failed:', e?.message || e);
      }
      // One client per project — keep the first linked company if older data has more.
      clients = (clients || []).slice(0, 1);
      const client_ids = clients.map((c) => c.id);
      const client_name = formatClientNames(clients);
      const { client_id: _legacy, ...rest } = project;
      return {
        ...rest,
        clients,
        client_ids,
        client_name,
        client_id: client_ids[0] ?? null,
      };
    },

    async findClientByName(name) {
      const q = (name || '').trim().toLowerCase();
      if (!q) return null;
      const clients = await listClients();
      return clients.find((c) => (c.name || '').trim().toLowerCase() === q) || null;
    },

    async findClientByShortCode(code) {
      const q = (code || '').trim().toUpperCase();
      if (!q) return null;
      if (!isDbMode()) {
        return getData().clients.find((c) => String(c.short_code || '').toUpperCase() === q) || null;
      }
      return dbSelect('clients', { filters: { short_code: q }, maybeSingle: true });
    },

    async findOrCreateClient(name, shortCode = null) {
      const store = getStore();
      const trimmed = (name || '').trim();
      if (!trimmed && !shortCode) return null;
      if (shortCode) {
        const byCode = await store.findClientByShortCode(shortCode);
        if (byCode) return byCode.id;
      }
      if (trimmed) {
        const existing = await store.findClientByName(trimmed);
        if (existing) {
          if (shortCode && !existing.short_code) {
            await store.updateClient(existing.id, { short_code: shortCode });
          }
          return existing.id;
        }
      }
      return store.addClient({
        name: trimmed || String(shortCode).trim(),
        short_code: shortCode ? String(shortCode).trim().toUpperCase() : null,
      });
    },

    async addClient(row) {
      const created_at = new Date().toISOString();
      const { contact_name: _cn, email: _e, phone: _p, ...company } = row;
      const payload = {
        name: (company.name || '').trim(),
        short_code: company.short_code != null ? String(company.short_code).trim().toUpperCase() || null : null,
        created_at,
      };
      if (company.logo_url !== undefined) {
        payload.logo_url = company.logo_url || null;
      }
      if (!isDbMode()) {
        const data = getData();
        const id = nextId(data.clients);
        data.clients.push({ id, ...payload });
        save();
        return id;
      }
      try {
        const saved = await dbInsert('clients', payload);
        return saved.id;
      } catch (e) {
        if (!isMissingColumnError(e)) throw e;
        const ensured = await ensureClientsSchema();
        if (!ensured) {
          const err = new Error(missingClientsSchemaMessage(e));
          err.status = 503;
          throw err;
        }
        try {
          const saved = await dbInsert('clients', payload);
          return saved.id;
        } catch (retryErr) {
          if (isMissingColumnError(retryErr) && payload.logo_url !== undefined) {
            // Logo is optional; short_code is not.
            const withoutLogo = { ...payload };
            delete withoutLogo.logo_url;
            if (payload.short_code != null && /short_code/i.test(String(retryErr?.message || ''))) {
              const err = new Error(missingClientsSchemaMessage(retryErr));
              err.status = 503;
              throw err;
            }
            if (/logo_url/i.test(String(retryErr?.message || ''))) {
              console.warn('clients: inserting without logo_url after ensure');
              const saved = await dbInsert('clients', withoutLogo);
              return saved.id;
            }
          }
          if (isMissingColumnError(retryErr)) {
            const err = new Error(missingClientsSchemaMessage(retryErr));
            err.status = 503;
            throw err;
          }
          throw retryErr;
        }
      }
    },

    async addClientContact(row) {
      const payload = {
        client_id: row.client_id,
        contact_name: row.contact_name || null,
        email: row.email || null,
        phone: row.phone || null,
        created_at: new Date().toISOString(),
      };
      if (!isDbMode()) {
        const data = getData();
        if (!data.client_contacts) data.client_contacts = [];
        const id = nextId(data.client_contacts);
        data.client_contacts.push({ id, ...payload });
        save();
        return id;
      }
      try {
        const saved = await dbInsert('client_contacts', payload);
        return saved.id;
      } catch (e) {
        if (!isMissingColumnError(e) || !/client_contacts/i.test(String(e?.message || e || ''))) throw e;
        const ensured = await ensureClientsSchema();
        if (!ensured) {
          const err = new Error(missingClientsSchemaMessage(e));
          err.status = 503;
          throw err;
        }
        try {
          const saved = await dbInsert('client_contacts', payload);
          return saved.id;
        } catch (retryErr) {
          if (isMissingColumnError(retryErr)) {
            const err = new Error(missingClientsSchemaMessage(retryErr));
            err.status = 503;
            throw err;
          }
          throw retryErr;
        }
      }
    },

    async updateClient(id, row) {
      const patch = { ...row };
      delete patch.contact_name;
      delete patch.email;
      delete patch.phone;
      if (patch.name !== undefined) patch.name = (patch.name || '').trim();
      if (!isDbMode()) {
        const data = getData();
        const i = data.clients.findIndex((c) => c.id === id);
        if (i === -1) return false;
        data.clients[i] = { ...data.clients[i], ...patch };
        save();
        return true;
      }
      try {
        const saved = await dbUpdate('clients', id, patch);
        return Boolean(saved);
      } catch (e) {
        if (!isMissingColumnError(e)) throw e;
        const ensured = await ensureClientsSchema();
        if (!ensured) {
          const err = new Error(missingClientsSchemaMessage(e));
          err.status = 503;
          throw err;
        }
        try {
          const saved = await dbUpdate('clients', id, patch);
          return Boolean(saved);
        } catch (retryErr) {
          // Never silently drop short_code — it is required identity data.
          if (isMissingColumnError(retryErr) && patch.short_code !== undefined
            && /short_code/i.test(String(retryErr?.message || ''))) {
            const err = new Error(missingClientsSchemaMessage(retryErr));
            err.status = 503;
            throw err;
          }
          if (isMissingColumnError(retryErr) && patch.logo_url !== undefined
            && /logo_url/i.test(String(retryErr?.message || ''))) {
            console.warn('clients: updating without logo_url after ensure');
            const withoutLogo = { ...patch };
            delete withoutLogo.logo_url;
            const saved = await dbUpdate('clients', id, withoutLogo);
            return Boolean(saved);
          }
          if (isMissingColumnError(retryErr)) {
            const err = new Error(missingClientsSchemaMessage(retryErr));
            err.status = 503;
            throw err;
          }
          throw retryErr;
        }
      }
    },

    async updateClientContact(id, row) {
      if (!isDbMode()) {
        const data = getData();
        if (!data.client_contacts) data.client_contacts = [];
        const i = data.client_contacts.findIndex((cc) => cc.id === id);
        if (i === -1) return false;
        data.client_contacts[i] = {
          ...data.client_contacts[i],
          contact_name: row.contact_name !== undefined ? row.contact_name || null : data.client_contacts[i].contact_name,
          email: row.email !== undefined ? row.email || null : data.client_contacts[i].email,
          phone: row.phone !== undefined ? row.phone || null : data.client_contacts[i].phone,
        };
        save();
        return true;
      }
      const patch = {};
      if (row.contact_name !== undefined) patch.contact_name = row.contact_name || null;
      if (row.email !== undefined) patch.email = row.email || null;
      if (row.phone !== undefined) patch.phone = row.phone || null;
      const saved = await dbUpdate('client_contacts', id, patch);
      return Boolean(saved);
    },

    async deleteClientContact(id) {
      if (!isDbMode()) {
        const data = getData();
        if (!data.client_contacts) return false;
        const i = data.client_contacts.findIndex((cc) => cc.id === id);
        if (i === -1) return false;
        data.client_contacts.splice(i, 1);
        save();
        return true;
      }
      await dbDelete('client_contacts', id);
      return true;
    },

    async deleteClient(id) {
      if (!isDbMode()) {
        const data = getData();
        const i = data.clients.findIndex((c) => c.id === id);
        if (i === -1) return false;
        data.clients.splice(i, 1);
        if (data.client_contacts) {
          data.client_contacts = data.client_contacts.filter((cc) => cc.client_id !== id);
        }
        if (data.project_clients) {
          data.project_clients = data.project_clients.filter((pc) => pc.client_id !== id);
        }
        save();
        return true;
      }
      await dbDeleteWhere('client_contacts', { client_id: id });
      await dbDeleteWhere('project_clients', { client_id: id });
      await dbDelete('clients', id);
      return true;
    },

    async getClientContacts(clientId) {
      const cid = Number(clientId);
      if (!isDbMode()) {
        return (getData().client_contacts || []).filter((cc) => Number(cc.client_id) === cid);
      }
      return dbSelect('client_contacts', { filters: { client_id: cid }, order: 'id' });
    },
  };
}
