-- Backlog items and project delivery phases (Fasa A–C)
create table if not exists public.backlogs_app (
  id bigint generated by default as identity primary key,
  ref_no text not null,
  project_id bigint not null references public.projects(id) on delete cascade,
  title text not null,
  description text,
  item_type text not null default 'scope',
  source text not null default 'manual',
  status text not null default 'new',
  priority text not null default 'medium',
  issue_id bigint,
  task_id bigint,
  assignee_person_id bigint references public.people(id) on delete set null,
  effort_days numeric,
  phase_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_backlogs_app_project_id on public.backlogs_app(project_id);
create index if not exists idx_backlogs_app_issue_id on public.backlogs_app(issue_id);

create table if not exists public.project_phases_app (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  phase_key text not null default 'custom',
  sort_order int not null default 0,
  status text not null default 'pending',
  target_date date,
  completed_date date,
  progress_percent int not null default 0,
  payment_amount numeric,
  payment_currency text not null default 'MYR',
  invoice_no text,
  invoice_date date,
  paid_date date,
  payment_status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_project_phases_app_project_id on public.project_phases_app(project_id);

alter table public.project_tasks add column if not exists backlog_id bigint;
