create table if not exists public.attachments_app (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  kind text not null default 'file',
  file_name text not null,
  mime_type text,
  file_size bigint,
  storage_path text,
  external_url text,
  label text,
  uploaded_by_user_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists idx_attachments_app_entity on public.attachments_app (entity_type, entity_id);
