-- Ensure PIC + project link tables exist (idempotent; may already exist from older migrations).
create table if not exists public.client_contacts (
  id bigint primary key generated by default as identity,
  client_id bigint not null references public.clients(id) on delete cascade,
  contact_name text,
  email text,
  phone text,
  created_at timestamptz not null default now()
);

create index if not exists idx_client_contacts_client_id on public.client_contacts(client_id);

create table if not exists public.project_clients (
  id bigint primary key generated by default as identity,
  project_id bigint not null references public.projects(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (project_id, client_id)
);

create index if not exists idx_project_clients_project_id on public.project_clients(project_id);
create index if not exists idx_project_clients_client_id on public.project_clients(client_id);

alter table public.clients
  add column if not exists short_code text;

alter table public.clients
  add column if not exists logo_url text;

create index if not exists clients_short_code_idx on public.clients (short_code);
