-- Many clients per project (junction table)
create table if not exists public.project_clients (
  id bigint primary key generated by default as identity,
  project_id bigint not null references public.projects(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (project_id, client_id)
);

create index if not exists idx_project_clients_project_id on public.project_clients(project_id);
create index if not exists idx_project_clients_client_id on public.project_clients(client_id);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'projects' and column_name = 'client_id'
  ) then
    insert into public.project_clients (project_id, client_id, created_at)
    select
      p.id,
      p.client_id,
      coalesce(p.created_at, now())
    from public.projects p
    where p.client_id is not null
      and not exists (
        select 1 from public.project_clients pc
        where pc.project_id = p.id and pc.client_id = p.client_id
      );

    alter table public.projects drop column client_id;
  end if;
end $$;
