-- Backlog workflow: Open / In progress / Fixed / Closed, creator tracking, comments

alter table public.backlogs_app
  add column if not exists created_by_user_id bigint references public.users_app(id) on delete set null;

update public.backlogs_app
set status = case lower(status)
  when 'new' then 'open'
  when 'triaged' then 'open'
  when 'approved' then 'open'
  when 'in_sprint' then 'in_progress'
  when 'done' then 'fixed'
  when 'rejected' then 'closed'
  else status
end
where lower(status) in ('new', 'triaged', 'approved', 'in_sprint', 'done', 'rejected');

alter table public.backlogs_app alter column status set default 'open';

create table if not exists public.backlog_comments_app (
  id bigint generated by default as identity primary key,
  backlog_id bigint not null references public.backlogs_app(id) on delete cascade,
  author_user_id bigint not null references public.users_app(id) on delete cascade,
  body text not null,
  mentioned_person_ids bigint[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists idx_backlog_comments_app_backlog_id on public.backlog_comments_app(backlog_id);
