-- Ensure in-app notifications table exists (idempotent).
create table if not exists public.notifications_app (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  type text not null default 'info',
  title text not null,
  body text,
  link text,
  entity_type text,
  entity_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_app_user_idx
  on public.notifications_app (user_id, read_at);

create index if not exists idx_notifications_app_user_created
  on public.notifications_app (user_id, created_at desc);

alter table public.notifications_app enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'notifications_app'
      and policyname = 'notifications_own_select'
  ) then
    create policy notifications_own_select on public.notifications_app
      for select to authenticated
      using (
        user_id::text = coalesce(auth.jwt() ->> 'app_user_id', auth.jwt() ->> 'sub', '')
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'notifications_app'
      and policyname = 'notifications_own_update'
  ) then
    create policy notifications_own_update on public.notifications_app
      for update to authenticated
      using (
        user_id::text = coalesce(auth.jwt() ->> 'app_user_id', auth.jwt() ->> 'sub', '')
      );
  end if;
end $$;
