-- Work packages: multiple delivery lines / project types within one project
create table if not exists public.project_work_packages_app (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  description text,
  classification text not null,
  status text not null default 'active',
  start_date date,
  end_date date,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_work_packages_app_project_id on public.project_work_packages_app(project_id);

alter table public.project_phases_app add column if not exists work_package_id bigint;
alter table public.backlogs_app add column if not exists work_package_id bigint;
alter table public.project_tasks add column if not exists work_package_id bigint;

create index if not exists idx_project_phases_app_work_package_id on public.project_phases_app(work_package_id);
create index if not exists idx_backlogs_app_work_package_id on public.backlogs_app(work_package_id);
create index if not exists idx_project_tasks_work_package_id on public.project_tasks(work_package_id);
