-- Helpdesk issues and in-app notifications
create table if not exists public.issues_app (
  id bigint generated by default as identity primary key,
  ticket_no text not null,
  title text not null,
  description text,
  status text not null default 'open',
  priority text not null default 'medium',
  category text not null default 'other',
  project_id bigint references public.projects(id) on delete set null,
  client_id bigint references public.clients(id) on delete set null,
  reporter_user_id bigint,
  assignee_person_id bigint references public.people(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.notifications_app (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  type text not null default 'info',
  title text not null,
  body text,
  link text,
  entity_type text,
  entity_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists issues_app_status_idx on public.issues_app (status);
create index if not exists issues_app_project_idx on public.issues_app (project_id);
create index if not exists notifications_app_user_idx on public.notifications_app (user_id, read_at);
